// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKp9tRK33D6W0bW6xQIHIshmzNSOfKAOU',
    appId: '1:623491228919:web:4454bb0f8546b8d84b5ff2',
    messagingSenderId: '623491228919',
    projectId: 'flutter-qualification-work',
    authDomain: 'flutter-qualification-work.firebaseapp.com',
    storageBucket: 'flutter-qualification-work.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUvnknKe6Sk5Se0MZnrNeiwgT59nMaF8Y',
    appId: '1:623491228919:android:63ee792fb5a824614b5ff2',
    messagingSenderId: '623491228919',
    projectId: 'flutter-qualification-work',
    storageBucket: 'flutter-qualification-work.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm1tDlWv8jKK7zcWJwQQ53OaY7GaKtBM8',
    appId: '1:623491228919:ios:d6061e7830966fa54b5ff2',
    messagingSenderId: '623491228919',
    projectId: 'flutter-qualification-work',
    storageBucket: 'flutter-qualification-work.appspot.com',
    iosBundleId: 'com.vlad345406.flutterQualificationWork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm1tDlWv8jKK7zcWJwQQ53OaY7GaKtBM8',
    appId: '1:623491228919:ios:f6b7ce17ce0ac69c4b5ff2',
    messagingSenderId: '623491228919',
    projectId: 'flutter-qualification-work',
    storageBucket: 'flutter-qualification-work.appspot.com',
    iosBundleId: 'com.vlad345406.flutterQualificationWork.RunnerTests',
  );
}
